car_dict = {
    "Acura": ["ILX", "TLX", "RLX", "MDX", "RDX", "NSX"],
    "Alfa Romeo": ["Giulia", "Stelvio", "4C", "8C"],
    "Aston Martin": ["DB11", "DBS Superleggera", "Vantage", "Rapide", "Valhalla"],
    "Audi": ["A4", "A6", "A8", "Q5", "Q7", "Q8", "R8", "TT", "e-tron"],
    "Bentley": ["Continental GT", "Bentayga", "Flying Spur", "Mulsanne"],
    "BMW": ["3 Series", "5 Series", "7 Series", "X3", "X5", "X7", "Z4", "i3", "i8"],
    "Bugatti": ["Chiron", "Divo", "Centodieci", "Veyron", "EB110"],
    "Buick": ["Enclave", "Encore", "Envision", "LaCrosse", "Regal"],
    "Cadillac": ["XT5", "XT6", "Escalade", "CT4", "CT5", "CT6", "ATS", "CTS", "XT4"],
    "Chevrolet": ["Silverado", "Equinox", "Tahoe", "Suburban", "Corvette", "Camaro", "Impala", "Malibu", "Traverse", "Trailblazer"],
    "Chrysler": ["300", "Pacifica", "Voyager"],
    "Dodge": ["Charger", "Challenger", "Durango", "Journey", "Caravan"],
    "Ferrari": ["488", "812", "SF90 Stradale", "Portofino", "Roma"],
    "Fiat": ["500", "500X", "500L", "124 Spider"],
    "Ford": ["F-150", "Explorer", "Escape", "Edge", "Mustang", "Focus", "Fusion", "Taurus", "Bronco", "Ranger"],
    "GMC": ["Sierra", "Acadia", "Terrain", "Yukon", "Canyon", "Envoy", "Jimmy", "Safari", "Suburban", "Syclone"],
    "Honda": ["Civic", "Accord", "CR-V", "Pilot", "Odyssey", "Fit", "HR-V", "Ridgeline", "Insight", "Passport"],
    "Hummer": ["H1", "H2", "H3", "HX", "H4"],
    "Hyundai": ["Elantra", "Sonata", "Santa Fe", "Tucson", "Palisade", "Kona", "Veloster", "Nexo"],
    "Infiniti": ["Q50", "Q60", "Q70", "QX50", "QX60", "QX70", "QX80", "I30", "G20", "G35"],
    "Jaguar": ["F-PACE", "F-TYPE", "XE", "XF", "XJ", "E-PACE", "I-PACE", "S-Type", "X-Type", "XK"],
    "Jeep": ["Wrangler", "Grand Cherokee", "Cherokee", "Renegade", "Compass", "Commander", "Patriot", "Gladiator"],
    "Kia": ["Sorento", "Sportage", "Optima", "Soul", "Telluride", "Rio", "Niro", "Sedona", "Stinger", "K900"],
    "Koenigsegg": ["Agera", "CCX", "Jesko", "Regera", "Gemera", "CCGT", "Quant", "CCR", "Trevita", "One:1"],
    "Lamborghini": ["Aventador", "Huracan", "Urus", "Gallardo", "Countach", "Diablo", "Murcielago", "Reventon", "Sesto Elemento", "Centenario"],
    "Land Rover": ["Range Rover", "Range Rover Sport", "Discovery", "Evoque", "Defender", "Velar", "Freelander"],
    "Lexus": ["ES", "LS", "RX", "GX", "LX", "IS", "RC", "LC", "CT", "UX"],
    "Lincoln": ["Navigator", "Aviator", "Continental", "Nautilus", "MKC", "MKT", "MKZ", "Town Car", "Mark LT"],
    "Lotus": ["Evora", "Exige", "Elise", "Esprit", "Europa", "Elan", "Eclat", "Elite", "Seven", "340R"],
    "Maserati": ["Quattroporte", "Ghibli", "Levante", "GranTurismo", "GranCabrio", "MC20", "3200 GT", "3500 GT", "Mistral", "Sebring"],
    "Mazda": ["CX-5", "CX-9", "Mazda3", "Mazda6", "MX-5 Miata", "RX-8", "Tribute", "Protege", "626", "RX-7"],
    "McLaren": ["720S", "570S", "600LT", "650S", "P1", "Senna", "F1", "Speedtail", "540C", "GT"],
    "Mercedes-Benz": ["S-Class", "E-Class", "C-Class", "GLE", "GLC", "CLA", "AMG GT", "GLS", "SL-Class", "G-Class"],
    "Mini": ["Cooper", "Countryman", "Clubman", "Convertible", "Coupe", "Roadster", "Paceman", "John Cooper Works GP", "Cooper S", "Clubvan"],
    "Mitsubishi": ["Outlander", "Mirage", "Eclipse Cross", "Montero", "Lancer", "Mirage G4", "Raider", "Galant", "Endeavor", "3000GT"],
    "Nissan": ["Altima", "Maxima", "Rogue", "Murano", "Pathfinder", "GT-R", "Sentra", "Versa", "370Z", "Armada"],
    "Pagani": ["Huayra", "Zonda", "Cinque", "Tricolore", "R"],
    "Peugeot": ["208", "308", "508", "2008", "3008", "5008", "108", "307", "407", "807"],
    "Porsche": ["911", "Cayenne", "Panamera", "Macan", "Boxster", "Cayman", "918 Spyder", "Carrera GT", "Taycan", "959"],
    "Ram": ["1500", "2500", "3500", "4500", "5500", "ProMaster", "ProMaster City"],
    "Rolls-Royce": ["Ghost", "Phantom", "Wraith", "Cullinan", "Dawn", "Silver Ghost", "Silver Wraith", "Silver Cloud", "Silver Shadow", "Silver Spirit"],
    "Subaru": ["Outback", "Legacy", "Impreza", "Forester", "WRX", "Crosstrek", "Ascent", "Baja", "BRZ", "XV Crosstrek"],
    "Tesla": ["Model S", "Model X", "Model Y", "Model 3", "Roadster", "Cybertruck", "Semi", "Powerwall", "Powerpack", "Solar Panel"],
    "Toyota": ["Camry", "Corolla", "RAV4", "Highlander", "Tacoma", "Tundra", "4Runner", "Prius", "Sienna", "Land Cruiser"]
}

